name: PyPIRelease

on:
  release:
    types: [published]

jobs:
  build:
    if: github.event.release.prerelease == false && github.event.release.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          version: "0.12.4"

      - name: Install the project
        run: uv sync --locked --managed-python --no-default-groups

      - name: Build
        run: uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v7
        with:
          name: distributions
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/BHResist
    permissions:
      id-token: write

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v8
        with:
          name: distributions
          path: dist/

      - name: Deploy on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
